use_frameworks!
platform :ios, '9.3'

target 'PaymentValidator_Example' do
  pod 'PaymentValidator', :path => '../'
  pod 'FlatDropdown', '~> 0.0.1'

  target 'PaymentValidator_Tests' do
    inherit! :search_paths

  end
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
